name: Setup
description: setup node and npm

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24.11.0
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci
